// fetch() on wx, over wx.request. Pages written against the web/fjs fetch
// surface (the fetch.vue example, any dependency doing `await fetch(...)`)
// keep working without source changes. Only the JSON-text surface is
// implemented: wx.request has no streaming, so response bodies are buffered
// whole — same as the QuickJS host binding, just platform-side.
//
// Installed once on module load (see index.ts); wx.request's timeout and
// header restrictions apply as documented by WeChat.

interface WxRequestResult {
  statusCode: number;
  data: unknown;
  header?: Record<string, string>;
  errMsg?: string;
}

// wx itself comes from the ambient declarations in env.d.ts; the request
// option fields used here are the documented subset.

import { base64Decode } from '../net/base64';
import { utf8Decode } from '../ui/utf8';

/** public/ data files by URL, each a lazy loader of its base64 bytes —
 * generated by `fjs build --mp` (fjs/public-data.js) and handed over by
 * app.ts. A real device cannot read the code package through
 * FileSystemManager, so this map is how those files reach fetch at all. */
let publicData: Record<string, () => string> = {};

export function registerPublicData(table: Record<string, () => string>): void {
  publicData = table;
}

export function installFetchPolyfill(): void {
  const g = globalThis as Record<string, unknown>;
  if (typeof g.fetch === 'function') return;

  g.fetch = ((input: RequestInfo | URL, init: RequestInit = {}): Promise<Response> => {
    const url = typeof input === 'string' ? input : String((input as URL).toString());
    const method = (init.method ?? 'GET').toUpperCase();
    const headers = normalizeHeaders(init.headers);
    const body = init.body;
    if (isPackagePath(url) && method === 'GET') return readPackageFile(url);
    return new Promise((resolve, reject) => {
      wx.request({
        url,
        method,
        header: headers,
        data: body === undefined || body === null ? undefined : String(body),
        responseType: 'text',
        dataType: 'text', // any non-'json' value disables wx's implicit JSON.parse
        success: (res: WxRequestResult) => resolve(makeResponse(url, res)),
        fail: (res: { errMsg: string }) => reject(new TypeError(`fetch failed: ${res.errMsg}`)),
      });
    });
  }) as typeof fetch;
}

/** `/spine/x.atlas`: root-absolute, the same URL public/ files have on web
 * and the app. wx.request rejects it ("invalid url") — there is no origin to
 * resolve it against — but the build ships public/ inside the code package
 * at exactly that path. `//host/x` is protocol-relative, not a package path. */
function isPackagePath(url: string): boolean {
  return url.startsWith('/') && !url.startsWith('//');
}

function readFile(filePath: string): Promise<ArrayBuffer> {
  return new Promise((resolve, reject) => {
    wx.getFileSystemManager().readFile({
      filePath,
      success: (res: { data: ArrayBuffer }) => resolve(res.data),
      fail: (res: { errMsg: string }) => reject(new Error(res.errMsg)),
    });
  });
}

/** The build's public data map first; FileSystemManager only as a fallback
 * (it sees the package in DevTools, not on a device). A file in neither
 * place answers 404 like a server would, so `response.ok` stays meaningful. */
async function readPackageFile(url: string): Promise<Response> {
  const filePath = url.split(/[?#]/)[0];
  const load = publicData[filePath];
  if (load) {
    return makeBytesResponse(url, 200, base64Decode(load()));
  }
  try {
    return makeBytesResponse(url, 200, new Uint8Array((await readFile(filePath)) as ArrayBuffer));
  } catch {
    return makeBytesResponse(url, 404, new Uint8Array(0));
  }
}

function makeBytesResponse(url: string, status: number, bytes: Uint8Array): Response {
  const text = () => utf8Decode(bytes);
  return {
    ok: status >= 200 && status < 300,
    status,
    statusText: status === 404 ? 'Not Found' : '',
    url,
    redirected: false,
    type: 'basic' as const,
    headers: { get: () => null, has: () => false },
    text: () => Promise.resolve(text()),
    json: () => Promise.resolve(JSON.parse(text()) as unknown),
    arrayBuffer: () =>
      Promise.resolve(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer),
    blob: () => Promise.reject(new Error('response.blob() is not supported on wx')),
    formData: () => Promise.reject(new Error('response.formData() is not supported on wx')),
    clone: () => {
      throw new Error('response.clone() is not supported on wx');
    },
    bodyUsed: false,
    body: null,
  } as unknown as Response;
}

function normalizeHeaders(init: HeadersInit | undefined): Record<string, string> {
  const out: Record<string, string> = {};
  if (!init) return out;
  if (Array.isArray(init)) {
    for (const [k, v] of init) out[k] = v;
  } else {
    Object.assign(out, init);
  }
  return out;
}

function makeResponse(url: string, res: WxRequestResult): Response {
  const text = typeof res.data === 'string' ? res.data : JSON.stringify(res.data ?? null);
  const headers = new Map(
    Object.entries(res.header ?? {}).map(([k, v]) => [k.toLowerCase(), String(v)]),
  );
  return {
    ok: res.statusCode >= 200 && res.statusCode < 300,
    status: res.statusCode,
    statusText: '',
    url,
    redirected: false,
    type: 'basic' as const,
    headers: {
      get: (name: string) => headers.get(name.toLowerCase()) ?? null,
      has: (name: string) => headers.has(name.toLowerCase()),
    },
    text: () => Promise.resolve(text),
    json: () => Promise.resolve(JSON.parse(text) as unknown),
    arrayBuffer: () => Promise.resolve(new TextEncoder().encode(text).buffer as ArrayBuffer),
    blob: () => Promise.reject(new Error('response.blob() is not supported on wx')),
    formData: () => Promise.reject(new Error('response.formData() is not supported on wx')),
    clone: () => {
      throw new Error('response.clone() is not supported on wx');
    },
    bodyUsed: false,
    body: null,
  } as unknown as Response;
}
