// Ambient declarations for the `fjs*` specifiers.
//
// Builds alias these to the right implementation per target (see
// flutterAliases()/webAliases() in the toolchain); the editor and vue-tsc
// need the same names to resolve to *something*, and it may as well be the
// package that ships them. Projects used to spell this out as `paths` in
// their own tsconfig.json, which meant every project carried a copy of a
// mapping that only this package can keep correct.
//
// A project picks these up with one line in a .d.ts it already has:
//
//   /// <reference types="@ufjs/runtime/ambient" />
//
// That line also brings in native-global.d.ts — the `__fjs` object the
// engine installs — so app code that reaches past the wrappers still has
// types for it, and fetch-global.d.ts for the fetch globals the runtime
// installs.
//
// This file must stay a *script*, not a module: `declare module` in a file
// with top-level import/export is augmentation, which requires the module
// to already resolve. Imports inside the blocks below are fine.
//
// 'fjs/pages' and 'fjs/plugins' are generated by the toolchain, but their
// *shape* is fixed and their types are this package's, so they are
// declared here too rather than copied into every project. What does vary
// per project is the route *names*, and those stay in the generated
// src/fjs-routes.d.ts.

/// <reference path="./native-global.d.ts" />
/// <reference path="./fetch-global.d.ts" />

declare module 'fjs' {
  export * from '@ufjs/runtime';
}

declare module 'fjs/vue' {
  export * from '@ufjs/runtime/vue';
}

declare module 'fjs/router' {
  export * from '@ufjs/runtime/router';
}

declare module 'fjs/app' {
  export * from '@ufjs/runtime/app';
}

declare module 'fjs/web' {
  export * from '@ufjs/runtime/web';
}

declare module 'fjs/pages' {
  import type { RouteRecord } from 'fjs/router';

  export const routes: RouteRecord[];
  export default routes;
}

declare module 'fjs/plugins' {
  import type { FjsPlugin } from 'fjs/app';

  export const plugins: FjsPlugin[];
  export default plugins;
}
