// How many nodes rich-text puts on the Flutter side (specs/035).
//
// Mounts FjsRichText through the Flutter renderer, decodes the op frames and
// counts Create ops by what the node is: a view, a paragraph text, a span
// text inside a text, or a bare text leaf. Node count is what an old iPhone
// pays for (JS objects the GC walks, mirror nodes, widget views), so it is
// pinned here rather than left to a device run to notice.
//
// The long article is generated by the same rule as the 「长文」 panel in
// examples/hello-fjs/src/pages/comp/rich-text.vue, which measures the time.
import { appendFileSync } from 'node:fs';
import { beforeAll, describe, expect, it } from 'vitest';
import { defineComponent, h, type VNode } from '@vue/runtime-core';
import { setOpSink } from '../src/host';
import { createApp, flutterRoot } from '../src/vue';
import { UiOp as Op } from '../src/ui/ops';
import { FjsRichText } from '../src/components/rich-text';

// the interned style encoding (ops 7-9), as a real host declares it
(globalThis as { __fjsHost?: { uiOpsVersion: number } }).__fjsHost = { uiOpsVersion: 2 };

const frames: Uint8Array[] = [];
// the sink hands over a view of the writer's buffer, which the next frame reuses
beforeAll(() => setOpSink((frame) => frames.push(frame.slice())));

async function flush(): Promise<void> {
  for (let i = 0; i < 50; i++) await Promise.resolve();
}

export interface NodeCount {
  total: number;
  view: number;
  paragraph: number;
  span: number;
  leaf: number;
  other: number;
  bytes: number;
  /** id → tag, and which ids got SetText, for structural assertions. */
  tag: Map<number, string>;
  parent: Map<number, number>;
  text: Map<number, string>;
  props: Map<number, Record<string, unknown>>;
}

function decode(): NodeCount {
  const tag = new Map<number, string>();
  const kids = new Map<number, number>();
  const parent = new Map<number, number>();
  const text = new Map<number, string>();
  const props = new Map<number, Record<string, unknown>>();
  const dec = new TextDecoder();
  let bytes = 0;
  for (const frame of frames) {
    bytes += frame.length;
    const view = new DataView(frame.buffer, frame.byteOffset, frame.byteLength);
    let i = 0;
    const u32 = () => {
      const v = view.getUint32(i, true);
      i += 4;
      return v;
    };
    const u16 = () => {
      const v = view.getUint16(i, true);
      i += 2;
      return v;
    };
    // NOTE: never `i += u32()` — the compound assignment reads `i` before
    // u32() advances it
    const str = (len: number) => {
      const s = dec.decode(frame.subarray(i, i + len));
      i += len;
      return s;
    };
    while (i < frame.length) {
      const op = frame[i++];
      switch (op) {
        case Op.Create: {
          const id = u32();
          tag.set(id, str(u16()));
          break;
        }
        case Op.Remove:
          u32();
          break;
        case Op.Insert: {
          const p = u32();
          const c = u32();
          u32();
          kids.set(p, (kids.get(p) ?? 0) + 1);
          parent.set(c, p);
          break;
        }
        case Op.RemoveChild:
          u32();
          u32();
          break;
        case Op.SetText: {
          const id = u32();
          text.set(id, str(u32()));
          break;
        }
        case Op.SetProps: {
          const id = u32();
          props.set(id, { ...(props.get(id) ?? {}), ...JSON.parse(str(u32())) });
          break;
        }
        case Op.DefineStyle: {
          u32();
          const len = u32();
          i += len;
          break;
        }
        case Op.SetStyle:
          u32();
          u32();
          u32();
          break;
        case Op.ResetStyles:
          break;
        default:
          throw new Error(`unknown op ${op} at ${i - 1}`);
      }
    }
  }
  const count: NodeCount = { total: tag.size, view: 0, paragraph: 0, span: 0, leaf: 0, other: 0, bytes, tag, parent, text, props };
  for (const [id, t] of tag) {
    if (t === 'view') count.view++;
    else if (t === 'text') {
      const p = parent.get(id);
      if (text.has(id) && !kids.get(id) && p !== undefined && tag.get(p) === 'text') count.leaf++;
      else if (p !== undefined && tag.get(p) === 'text') count.span++;
      else count.paragraph++;
    } else count.other++;
  }
  return count;
}

async function mount(nodes: string): Promise<NodeCount> {
  frames.length = 0;
  const App = defineComponent(() => () => h(FjsRichText, { nodes }) as VNode);
  createApp(App).mount(flutterRoot());
  await flush();
  return decode();
}

export const SAMPLES = {
  basic:
    '<h3>限时活动</h3><p>满 <b style="color:#FA5151">199</b> 减 30，<i>仅限今日</i>&nbsp;&gt;</p>' +
    '<p><u>下划线</u>、<s>删除线</s>、<mark>高亮</mark>、<code>code</code>、<small>小字</small>、<big>大字</big>，<q>引号</q></p>' +
    '<p>第一行<br>第二行（br 换行）</p>',
  lists:
    '<ul><li>无序列表</li><li>第二项<ul><li>嵌套一层</li><li>嵌套两项<ul><li>第三层</li></ul></li></ul></li></ul>' +
    '<ol start="3" type="A"><li>从 C 开始</li><li>D</li></ol>' +
    '<ol type="i"><li>罗马数字</li><li>第二项</li><li>第三项</li></ol>',
  table:
    '<table><thead><tr><th>商品</th><th width="60">数量</th><th width="80">金额</th></tr></thead><tbody>' +
    '<tr><td>咖啡豆 500g</td><td width="60">2</td><td width="80">¥ 136</td></tr>' +
    '<tr><td>滤纸 100 张</td><td width="60">1</td><td width="80">¥ 18</td></tr>' +
    '<tr><td colspan="2">合计</td><td width="80"><b>¥ 154</b></td></tr></tbody></table>',
  article:
    '<h2>商品详情</h2>' +
    Array.from(
      { length: 30 },
      (_, i) =>
        `<p>第 ${i + 1} 段：这是一段<b>加粗</b>与<span style="color:#FA5151">红字</span>混排的说明文字，<i>斜体</i>收尾。</p>`,
    ).join('') +
    '<ul>' +
    Array.from({ length: 10 }, (_, i) => `<li>卖点 ${i + 1}</li>`).join('') +
    '</ul>' +
    '<table>' +
    Array.from({ length: 5 }, (_, r) => `<tr><td>规格 ${r}</td><td>值 ${r}</td><td>备注</td></tr>`).join('') +
    '</table>' +
    Array.from({ length: 3 }, () => '<p><img src="/images/test-square.png" width="120"></p>').join(''),
};

/** Budgets from specs/035 §6.3. Before 035 (main at 5d307bb) the same
 * content was basic 42 · lists 67 · table 41 · article 486. Raising one needs
 * a reason written into the spec's tasks.md, not a quiet bump. */
const BUDGET: Record<keyof typeof SAMPLES, number> = {
  basic: 8,
  lists: 40,
  table: 24,
  article: 120,
};

describe('rich-text node count (Flutter renderer)', () => {
  it.each(Object.keys(SAMPLES) as Array<keyof typeof SAMPLES>)('%s stays within budget', async (name) => {
    const count = await mount(SAMPLES[name]);
    // FJS_NODE_REPORT=/some/file npx vitest run test/rich-text-node-budget.test.ts
    // appends the composition the numbers in docs/performance.md come from
    // (a file, not the console: this package's vitest run swallows logs)
    if (process.env.FJS_NODE_REPORT) {
      const { total, view, paragraph, span, leaf, other, bytes } = count;
      appendFileSync(
        process.env.FJS_NODE_REPORT,
        `${name}: ${JSON.stringify({ total, view, paragraph, span, leaf, other, bytes })}\n`,
      );
    }
    expect(count.total).toBeGreaterThan(0);
    expect(count.total).toBeLessThanOrEqual(BUDGET[name]);
    // no bare text node under a text: lone strings are element text and a
    // paragraph's runs are one prop
    expect(count.leaf).toBe(0);
  });

  it('carries a mixed paragraph as one node with richSpans', async () => {
    const count = await mount('<p>满 <b style="color:#FA5151">199</b> 减 30</p>');
    // flutterRoot()'s own container, the rich-text root view, the paragraph
    // (the budgets above count the container too, before and after 035)
    expect(count.total).toBe(3);
    const [id] = [...count.tag].find(([, tag]) => tag === 'text')!;
    expect(count.props.get(id)?.richSpans).toEqual([
      '满 ',
      { t: '199', s: { fontWeight: 'bold', color: '#FA5151' } },
      ' 减 30',
    ]);
  });

  it('falls back to nested nodes for a class, keeping the words', async () => {
    const count = await mount('<p>a <span class="hl">b</span> c</p>');
    // the paragraph keeps three child nodes: "a ", the classed span (its lone
    // string is element text, so it has no child of its own), " c"
    const [paragraph] = [...count.tag].find(([id, tag]) => tag === 'text' && count.tag.get(count.parent.get(id)!) === 'view')!;
    expect([...count.parent.values()].filter((p) => p === paragraph)).toHaveLength(3);
    const words = [...count.text.values()].join('');
    expect(words).toBe('a b c');
    for (const props of count.props.values()) expect(props.richSpans).toBeUndefined();
  });

  it('falls back to nested nodes for an image, the image inside the paragraph', async () => {
    const count = await mount('<p>x <img src="/a.png" width="18"> y</p>');
    const [imageId] = [...count.tag].find(([, tag]) => tag === 'image')!;
    const paragraph = count.parent.get(imageId)!;
    expect(count.tag.get(paragraph)).toBe('text');
    expect([...count.text.values()].join('')).toBe('x  y');
  });
});

export { mount as mountRichTextForCount };
