// The module's build step. fjs runs this before every build, dev start and
// Vite start, because package.json says `"fjs": { "prepare": "./prepare.mjs" }`.
//
// An app that installs this module writes `<icon-mind name="agent" />` and
// nothing else: no script to copy, no config to add. This hook reads the
// app's sources, finds the icons it actually names, and writes what both
// targets read:
//
//   .fjs/modules/iconmind/icons.json   the shapes — imported by the web
//                                      stand-in as 'fjs/data/icons.json',
//                                      copied into the Flutter host's assets
//   .fjs/modules/iconmind/types.d.ts   the names as types, so <icon-mind />
//                                      completes and rejects a typo
//
// IconMind has 2,437 icons and both official packages are compile-time by
// design (tree shaking, const + AOT). Scanning keeps that property without
// making the app maintain a list: what a page writes is what the app ships.
//
// Names that are not literals — from an API, from a route param — cannot be
// scanned, so they go in an optional file at the project root:
//
//   iconmind.json   { "icons": ["rag-pipeline", "shield-ellipsis"] }
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require_ = createRequire(import.meta.url);

/** <icon-mind name="agent" /> and its bound spellings, in templates and in
 * render functions:  name="x"  :name="'x'"  name: 'x' next to an icon-mind. */
const USES = [
  /<icon-mind\b[^>]*?\bname\s*=\s*"([a-z0-9-]+)"/gs,
  /<icon-mind\b[^>]*?\s:name\s*=\s*"'([a-z0-9-]+)'"/gs,
  /<icon-mind\b[^>]*?\s:name\s*=\s*'"([a-z0-9-]+)"'/gs,
];

export default async function prepare(ctx) {
  const wanted = new Set();
  for (const file of ctx.sources()) {
    const source = fs.readFileSync(file, 'utf8');
    if (!source.includes('icon-mind')) continue;
    for (const re of USES) {
      for (const match of source.matchAll(re)) wanted.add(match[1]);
    }
  }

  // names the app builds at runtime, which no scan can see
  const extra = path.join(ctx.root, 'iconmind.json');
  if (fs.existsSync(extra)) {
    const declared = JSON.parse(fs.readFileSync(extra, 'utf8')).icons;
    if (!Array.isArray(declared)) {
      throw new Error('iconmind.json must be { "icons": ["slug", …] }');
    }
    for (const name of declared) wanted.add(name);
  }

  const set = iconSet();
  const icons = {};
  const missing = [];
  for (const slug of [...wanted].sort()) {
    const file = set.icons.get(slug);
    if (!file) {
      missing.push(slug);
      continue;
    }
    const icon = JSON.parse(fs.readFileSync(file, 'utf8'));
    icons[slug] = icon.shapes.map((shape) => [shape.d, shape.closed ? 1 : 0]);
  }

  // A name that does not exist would be a blank space at runtime; say so now,
  // with the closest slugs the set does have.
  if (missing.length > 0) {
    const lines = missing.map((slug) => {
      const near = [...set.icons.keys()]
        .filter((name) => name.includes(slug.split('-')[0]))
        .slice(0, 5);
      return `  ${slug}${near.length ? `   did you mean: ${near.join(', ')}` : ''}`;
    });
    throw new Error(
      `no such icon in IconMind ${set.version} (${set.icons.size} icons):\n${lines.join('\n')}\n` +
        'browse them at https://iconmind.dev/icons',
    );
  }

  const slugs = Object.keys(icons);
  ctx.write('icons.json', JSON.stringify(icons));
  ctx.write(
    'types.d.ts',
    `// generated by the iconmind module — do not edit\n` +
      `// the icons this app names, so <icon-mind name="…" /> completes\n` +
      `interface FjsIcons {\n${slugs.map((s) => `  ${JSON.stringify(s)}: true;`).join('\n')}\n}\n`,
  );
  ctx.log(
    slugs.length === 0
      ? 'no <icon-mind /> in this app yet'
      : `${slugs.length} icons: ${slugs.join(', ')}`,
  );
}

/** The published set this module draws from. */
function iconSet() {
  const dir = path.dirname(require_.resolve('@iconmind/icons/package.json'));
  const version = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8')).version;
  const icons = new Map();
  const iconsDir = path.join(dir, 'icons');
  for (const category of fs.readdirSync(iconsDir)) {
    const categoryDir = path.join(iconsDir, category);
    if (!fs.statSync(categoryDir).isDirectory()) continue;
    for (const slug of fs.readdirSync(categoryDir)) {
      const file = path.join(categoryDir, slug, `${slug}.json`);
      if (fs.existsSync(file)) icons.set(slug, file);
    }
  }
  return { version, icons };
}
