// The decode path a camera frame takes, tested without a camera.
//
// The fixture is the QR `fjs dev` actually prints — generated by the same
// encoder the CLI uses (qrcode-generator, byte mode, ECC M) — rasterised
// here the way a camera hands frames over: a padded luminance plane with a
// row stride wider than the image, grey rather than pure black and white.
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:fjs_go/src/qr_decode.dart';

const _address = 'http://10.0.0.2:38900';

/// `#` is a dark module. Straight out of `fjs dev`'s own encoder.
const List<String> _modules = [
  '#######.#..##...#.#######',
  '#.....#.###.###.#.#.....#',
  '#.###.#.#.##.#..#.#.###.#',
  '#.###.#..######...#.###.#',
  '#.###.#.###..#....#.###.#',
  '#.....#..###....#.#.....#',
  '#######.#.#.#.#.#.#######',
  '..........#.##.#.........',
  '#..#######.......#..#.###',
  '..#....#.#.##..##...####.',
  '#...#.#.#.#...##....##..#',
  '..####.#..#....###...####',
  '.###..##.####.##.##.....#',
  '##.......#...#.#.#.##..#.',
  '##..#.####.###.##.#..####',
  '#.##.#.#.###..##..#.#.#.#',
  '#..##.#.###...#.#####.##.',
  '........######..#...#..#.',
  '#######.##.#....#.#.##..#',
  '#.....#.###.#.#.#...#..##',
  '#.###.#.#...##########.##',
  '#.###.#.##....#.#.##.#.##',
  '#.###.#.....#.##.#..#.###',
  '#.....#...#...##...##.###',
  '#######.#....#####...#..#',
];

/// Rasterises [_modules] into a luminance plane.
///
/// [scale] px per module, [quiet] modules of white border, [pad] px of extra
/// surround, and a row stride [slack] bytes wider than the image — Android
/// pads camera planes, and reading them as width*height silently skews.
QrFrame _frame({
  int scale = 6,
  int quiet = 4,
  int pad = 20,
  int slack = 16,
  int dark = 30,
  int light = 225,
}) {
  final n = _modules.length;
  final side = (n + quiet * 2) * scale;
  final width = side + pad * 2;
  final height = side + pad * 2;
  final rowStride = width + slack;
  final bytes = Uint8List(rowStride * height)..fillRange(0, rowStride * height, light);
  for (var y = 0; y < height; y++) {
    final my = (y - pad) ~/ scale - quiet;
    if (my < 0 || my >= n) continue;
    for (var x = 0; x < width; x++) {
      final mx = (x - pad) ~/ scale - quiet;
      if (mx < 0 || mx >= n) continue;
      if (_modules[my][mx] == '#') bytes[y * rowStride + x] = dark;
    }
  }
  return QrFrame(
    bytes: bytes,
    rowStride: rowStride,
    width: width,
    height: height,
  );
}

void main() {
  test('reads the address out of a fjs dev QR code', () {
    expect(_frame().decode(), _address);
  });

  test('a padded row stride is not mistaken for image data', () {
    // the stride is what a naive width*height read gets wrong: every row
    // after the first slides sideways and nothing decodes
    expect(_frame(slack: 64).decode(), _address);
  });

  test('a low-contrast frame still decodes', () {
    // a phone pointed at a terminal never sees 0 and 255
    expect(_frame(dark: 70, light: 170).decode(), _address);
  });

  test('a frame with no code in it returns null, not an exception', () {
    final blank = Uint8List(200 * 220)..fillRange(0, 200 * 220, 180);
    final frame = QrFrame(bytes: blank, rowStride: 200, width: 190, height: 220);
    expect(frame.decode(), isNull);
  });
}
