// The project's local files, as types the editor can complete.
//
// Two directories, two meanings, two URL prefixes
// (specs/018-src-hints-and-html-dir):
//
//   public/images/x.png  ->  /images/x.png       vite's own contract
//   html/guide.html      ->  /html/guide.html    pages a <web-view> opens
//
// The directory name stays in the html/ URL on purpose: public/ and html/
// would otherwise share the root namespace and two files could collide over
// one path, which is a silent overwrite rather than an error.
//
// What comes out is `src/fjs-assets.d.ts`, an augmentation of the empty
// FjsImageAssets / FjsHtmlAssets interfaces the runtime declares
// (fjs-runtime/src/assets.ts). Generated types rather than a build-time
// existence check: the check would catch a typo eventually and could not
// answer "what files have I got?" at all, which is the question that costs
// the time. It is also the same machinery routes already use
// (project/pages.ts), so there is one pattern to learn, not two.
import fs from 'node:fs';
import path from 'node:path';

/** Name of the generated declaration file, relative to the project root. */
export const ASSET_TYPES_FILE = path.join('src', 'fjs-assets.d.ts');

const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg']);
const HTML_EXTENSIONS = new Set(['.html', '.htm']);

export interface LocalAssets {
  /** Root-absolute paths of every image under `public/`. */
  images: string[];
  /** Root-absolute paths of every html file under `html/`. */
  html: string[];
}

/** Every file under [dir], as paths relative to it, recursively. */
function walk(dir: string): string[] {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return [];
  const out: string[] = [];
  const visit = (abs: string, rel: string): void => {
    for (const entry of fs.readdirSync(abs, { withFileTypes: true })) {
      // dotfiles are the editor's and the OS's, not the app's
      if (entry.name.startsWith('.')) continue;
      const next = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) visit(path.join(abs, entry.name), next);
      else if (entry.isFile()) out.push(next);
    }
  };
  visit(dir, '');
  return out;
}

/** What this project ships, as the paths a page would write.
 *
 * `public/` is scanned for images only and `html/` for html only: the point
 * of two tables is that `<image src="/guide.html">` is a type error, so a
 * stray file of the wrong kind must not widen the other tag's union. */
export function scanLocalAssets(root: string): LocalAssets {
  const images = walk(path.join(root, 'public'))
    .filter((file) => IMAGE_EXTENSIONS.has(path.extname(file).toLowerCase()))
    .map((file) => `/${file}`);
  const html = walk(path.join(root, 'html'))
    .filter((file) => HTML_EXTENSIONS.has(path.extname(file).toLowerCase()))
    .map((file) => `/html/${file}`);
  return { images: images.sort(), html: html.sort() };
}

/** Source of `src/fjs-assets.d.ts`. */
export function assetTypesSource(assets: LocalAssets): string {
  const entries = (paths: string[]): string =>
    paths.map((file) => `    ${JSON.stringify(file)}: true;`).join('\n');
  return `// generated by fjs — do not edit
export {};

declare global {
  interface FjsImageAssets {
${entries(assets.images)}
  }

  interface FjsHtmlAssets {
${entries(assets.html)}
  }
}
`;
}

/** Writes the declaration file when it would change.
 *
 * Skipped entirely for a project with no local files and no existing file,
 * so a project that ships none never grows one. The "only write on change"
 * rule is not an optimization: the dev server and vite both watch this
 * directory, and a rewrite is a reload. */
export function writeAssetTypes(root: string, assets = scanLocalAssets(root)): void {
  const file = path.join(root, ASSET_TYPES_FILE);
  const empty = assets.images.length === 0 && assets.html.length === 0;
  if (empty && !fs.existsSync(file)) return;
  const source = assetTypesSource(assets);
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === source) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, source);
}
