// The app-plugin directory: `src/plugins/*.ts` -> the generated module
// 'fjs/plugins', which the app entry passes to createFjsApp.
//
// Same shape as pages.ts one level down: scan a conventional directory,
// emit a generated module, write a .d.ts so the editor knows about it. A
// plugin file default-exports `(app) => void` — usually `app.use(...)`.
//
//   src/plugins/pinia.ts        both targets
//   src/plugins/devtools.web.ts web build only
//   src/plugins/native.app.ts   Flutter build only
//
// Order is alphabetical by filename, which is stable across machines; a
// plugin that must run first can say so with a `10-` style prefix.
import fs from 'node:fs';
import path from 'node:path';
import type { Platform } from './pages.js';

export interface AppPlugin {
  /** Absolute path to the plugin file. */
  file: string;
  /** Filename without extension or platform suffix — `pinia`. */
  name: string;
  platforms: Platform[];
}

export function pluginsDir(root: string): string {
  return path.join(root, 'src', 'plugins');
}

const PLUGIN_FILE_RE = /\.(?:ts|js|mts|mjs)$/;

export function scanPlugins(root: string): AppPlugin[] {
  const dir = pluginsDir(root);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((entry) => PLUGIN_FILE_RE.test(entry) && !entry.endsWith('.d.ts'))
    .sort()
    .map((entry) => {
      const suffix = /\.(app|web)\.(?:ts|js|mts|mjs)$/.exec(entry);
      return {
        file: path.join(dir, entry),
        name: entry.replace(/\.(app|web)?\.?(?:ts|js|mts|mjs)$/, ''),
        platforms: suffix ? [suffix[1] as Platform] : (['app', 'web'] as Platform[]),
      };
    });
}

export function pluginsFor(root: string, platform: Platform): AppPlugin[] {
  return scanPlugins(root).filter((plugin) => plugin.platforms.includes(platform));
}

/** Source of the generated 'fjs/plugins' module. */
export function pluginTableSource(plugins: AppPlugin[]): string {
  const head = ['// generated by fjs — do not edit'];
  const names: string[] = [];
  plugins.forEach((plugin, i) => {
    head.push(`import __fp${i} from ${JSON.stringify(plugin.file)};`);
    names.push(`__fp${i}`);
  });
  return `${head.join('\n')}\nexport const plugins = [${names.join(
    ', ',
  )}];\nexport default plugins;\n`;
}

/** Name of the generated declaration file, relative to the project root. */
export const PLUGIN_TYPES_FILE = path.join('src', 'fjs-plugins.d.ts');

export function pluginTypesSource(): string {
  return `// generated by fjs — do not edit
declare module 'fjs/plugins' {
  import type { FjsPlugin } from 'fjs/app';

  export const plugins: FjsPlugin[];
  export default plugins;
}
`;
}

/** Writes the declaration file when it would change. Projects with no
 * src/plugins directory never grow the file. */
export function writePluginTypes(root: string, plugins = scanPlugins(root)): void {
  const file = path.join(root, PLUGIN_TYPES_FILE);
  if (plugins.length === 0 && !fs.existsSync(file)) return;
  const source = pluginTypesSource();
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === source) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, source);
}
