// The app-plugin directory: `src/plugins/*.ts` -> the generated module
// 'fjs/plugins', which the app entry passes to createFjsApp.
//
// Same shape as pages.ts one level down: scan a conventional directory,
// emit a generated module. A plugin file default-exports `(app) => void`
// — usually `app.use(...)`. The module's *type* is declared once by
// @ufjs/runtime (src/ambient.d.ts), not generated per project.
//
//   src/plugins/pinia.ts        both targets
//   src/plugins/devtools.web.ts web build only
//   src/plugins/native.app.ts   Flutter build only
//
// Order is alphabetical by filename, which is stable across machines; a
// plugin that must run first can say so with a `10-` style prefix.
import fs from 'node:fs';
import path from 'node:path';
import type { Platform } from './pages.js';
import { moduleComponentsSource, type FjsModule } from './modules.js';

export interface AppPlugin {
  /** Absolute path to the plugin file. */
  file: string;
  /** Filename without extension or platform suffix — `pinia`. */
  name: string;
  platforms: Platform[];
}

export function pluginsDir(root: string): string {
  return path.join(root, 'src', 'plugins');
}

const PLUGIN_FILE_RE = /\.(?:ts|js|mts|mjs)$/;

export function scanPlugins(root: string): AppPlugin[] {
  const dir = pluginsDir(root);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((entry) => PLUGIN_FILE_RE.test(entry) && !entry.endsWith('.d.ts'))
    .sort()
    .map((entry) => {
      const suffix = /\.(app|web)\.(?:ts|js|mts|mjs)$/.exec(entry);
      return {
        file: path.join(dir, entry),
        name: entry.replace(/\.(app|web)?\.?(?:ts|js|mts|mjs)$/, ''),
        platforms: suffix ? [suffix[1] as Platform] : (['app', 'web'] as Platform[]),
      };
    });
}

export function pluginsFor(root: string, platform: Platform): AppPlugin[] {
  return scanPlugins(root).filter((plugin) => plugin.platforms.includes(platform));
}

/** Source of the generated 'fjs/plugins' module.
 *
 * [modules] contributes one plugin ahead of the project's own: the
 * registration of every module component as a global component, which is
 * what lets a page write <TestCard /> without importing anything. On web it
 * also registers the stand-ins for the modules' Flutter widgets. */
export function pluginTableSource(
  plugins: AppPlugin[],
  modules: FjsModule[] = [],
  platform: Platform = 'app',
): string {
  const head = ['// generated by fjs — do not edit'];
  const names: string[] = [];
  const { imports, register } = moduleComponentsSource(modules, platform);
  if (register.length > 0) {
    head.push(...imports);
    names.push('__fjsModuleComponents');
  }
  plugins.forEach((plugin, i) => {
    head.push(`import __fp${i} from ${JSON.stringify(plugin.file)};`);
    names.push(`__fp${i}`);
  });
  const registrar =
    register.length > 0
      ? `const __fjsModuleComponents = (app) => {\n${register.join('\n')}\n};\n`
      : '';
  return `${head.join('\n')}\n${registrar}export const plugins = [${names.join(
    ', ',
  )}];\nexport default plugins;\n`;
}
