// specs/049: worker files — src/workers/<rel>.ts|js → /workers/<rel>.js,
// bundled self-contained, wrapped for wx on the mini program.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { bundleWorker, scanWorkers, workerFileForUrl, wrapWxWorker, writeWorkers } from '../src/project/workers.js';
import { appJson } from '../src/mp/project.js';

let root: string;
const write = (rel: string, text: string) => {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
};

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'fjs-workers-'));
});
afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

describe('scanWorkers', () => {
  it('maps src/workers sources to /workers/*.js URLs', () => {
    write('src/workers/sqrt.ts', 'onmessage = () => {};');
    write('src/workers/nested/fib.js', 'onmessage = function () {};');
    write('src/workers/types.d.ts', 'declare const x: number;');
    expect(scanWorkers(root).map((w) => w.url)).toEqual(['/workers/nested/fib.js', '/workers/sqrt.js']);
    expect(workerFileForUrl(root, '/workers/sqrt.js')).toBe(path.join(root, 'src/workers/sqrt.ts'));
    expect(workerFileForUrl(root, '/workers/none.js')).toBeNull();
  });

  it('no src/workers: no workers', () => {
    expect(scanWorkers(root)).toEqual([]);
  });

  it('a.ts beside a.js is an error, not a silent pick', () => {
    write('src/workers/a.ts', '');
    write('src/workers/a.js', '');
    expect(() => scanWorkers(root)).toThrow(/two sources/);
  });
});

describe('bundleWorker / writeWorkers', () => {
  it('inlines local imports (@/ alias too) into one script', async () => {
    write('src/lib/math.ts', 'export const square = (n: number) => n * n;');
    write(
      'src/workers/sq.ts',
      "import { square } from '@/lib/math';\ndeclare function postMessage(m: string): void;\nonmessage = (e: any) => postMessage(String(square(Number(e.data))));",
    );
    const code = await bundleWorker(root, path.join(root, 'src/workers/sq.ts'));
    expect(code).not.toMatch(/\bimport\b/);
    expect(code).toContain('n * n');
    expect(code).toContain('onmessage =');
  });

  it('writes <dest>/workers and the mp wrapper around each script', async () => {
    write('src/workers/echo.js', 'onmessage = function (e) { postMessage(e.data); };');
    const dest = path.join(root, 'out');
    const urls = await writeWorkers(root, dest, { wrap: (code, entry) => wrapWxWorker(code, entry, root) });
    expect(urls).toEqual(['/workers/echo.js']);
    const text = fs.readFileSync(path.join(dest, 'workers/echo.js'), 'utf8');
    expect(text).toContain('// generated by fjs build --mp from src/workers/echo.js');
    expect(text).toContain('var onmessage = null;');
    expect(text).toContain('worker.postMessage({ d: String(message) })');
  });

  it('the wx wrapper routes onmessage / postMessage through the worker global', async () => {
    write('src/workers/echo.js', 'onmessage = function (e) { postMessage("got " + e.data); };');
    const [entry] = scanWorkers(root);
    const script = wrapWxWorker(await bundleWorker(root, entry.file), entry);
    const sent: unknown[] = [];
    let listener: ((m: unknown) => void) | null = null;
    const worker = { postMessage: (m: unknown) => sent.push(m), onMessage: (cb: (m: unknown) => void) => (listener = cb) };
    // strict mode, like the ES-module code a worker compiles to
    new Function('worker', `"use strict";\n${script}`)(worker);
    listener!({ d: 'hi' });
    expect(sent).toEqual([{ d: 'got hi' }]);
  });
});

describe('appJson workers', () => {
  it('declares the workers directory only when there are workers', () => {
    const pages = [{ path: '/', name: 'index', meta: {}, file: '/x/index.vue' }] as never;
    expect(JSON.parse(appJson(pages, 'skyline', { workers: true })).workers).toBe('workers');
    expect(JSON.parse(appJson(pages, 'skyline')).workers).toBeUndefined();
  });
});
